services:
  - type: web
    name: supportgenie-ai-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm run production
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true
